- hosts: all
  tasks:
    - name: stop container
      shell:  docker container stop rockstar-container                    #name of container 
    - name: remove container
      shell: docker container rm rockstar-container
    - name: remove docker image
      shell: docker image rm saikumar7550/docker-job2                            #name of images (docker images)
    - name: create new container
      shell: docker container run -itd --name rockstar-container -p 9000:80 saikumar7550/docker-job2
